version: '3'

services:
  frontend:
    image: 'yumyumfrontend:latest'
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 4200:4200
    expose:
      - 4200
  backend:
    image: 'yumyumbackend'
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    expose:
      - 8080          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123

networks:
  my_network: